### ISSUE TITLE
Shortcuts disabling themselves randomly

### ISSUE THREAD

**Issue by flabbet** [PixiEditor/PixiEditor#108]
**Describe as detailed as possible when it happens**
Shortcuts don't work randomly.

**Describe what you tried to do in order to fix it**
Always working shortcuts.

**Comment by Equbuxu** [comment]
To replicate: click the layer opacity textbox, press enter/tab. Now ctrl now longer works. To get it to work again, click any of the tool buttons (choosing a tool using keyboard works but doesn't fix ctrl)

**Comment by Equbuxu** [comment]
This might be caused by an invisible textbox inside NumberInput.xaml getting focus and consuming modifier key events, but I have not verified this
