### ISSUE TITLE
Undoing and redoing document resize destroys image quality

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#128]
To replicate: make a 256x256 canvas, draw something, Document->Resize Document->Resize to 200x200, undo, redo, undo, redo, undo...

Apart from destroying image quality this also breaks undo. If you try to undo one more time to remove the initial drawing it will attempt to undo the original high-quality version of the drawing and not the current version, leaving pixels behind.

**Comment by flabbet** [comment]
This is all related to the way how to undo for resizing is implemented, there are some other undo bugs, like copying and pasting clipboard, undo, save sth to the clipboard, paste, and boom, error. All of this will be fixed soon in one batch.
