### ISSUE TITLE
Add percentage/fraction input when changing document/canvas size

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#130]
Sometimes when changing image/document size you want to make it twice as big, or twice as small, or something similar. It would be useful to have an option to do this easily. One way to implement this would be making a dropdown with different units (pixels, percents/fraction, other can be added as well later)

**Comment by tomaszkot** [comment]
What do you think about a Radio Box approach, like : 

![image](https://user-images.githubusercontent.com/2432291/149661444-96c3efd4-f7f8-45e1-84df-76d30e7a0b35.png)

**Comment by flabbet** [comment]
Yeah, this has some potential. We would need to style it quite nicely

**Comment by Equbuxu** [comment]
Percentage should be separate for width and height just like pixels. I would add a dropdown titled "units" where you can choose pixels or percents

**Comment by tomaszkot** [comment]
> Percentage should be separate for width and height just like pixels.

If we really go into that direction, then yes combo is a way to go. I assumed most of the time user choosing 'Percentage' wants them the same in both axes.  In the long run combo approach is more flexible.

**Comment by Equbuxu** [comment]
Now that I think about it a single percentage field might be fine too, having different percentages is a rare use case. But then looking at your example the radio box is kinda redundant, as the values in the other field can be recalculated when the percentage changes (similar to the way those fields behave when Preserve Aspect Ratio is enabled).

@tomaszkot do you have any plans to work on this issue or should I take a crack at it

**Comment by tomaszkot** [comment]
As @flabbet mentioned the other option would be disabled. If you do not provide radio boxes user would be confused which option would be applied.

I can work on that issue at the end of the week. If you can do it earlier or just feel like doing it - fell free to do so.

**Comment by tomaszkot** [comment]
I finally did it :)

**Comment by Equbuxu** [comment]
> I finally did it :)
I've done quite a bit of work updating dialogs (but haven't worked on this issue yet). Could you try to rebase your branch onto dialogs-revamp and PR into there? Hopefully you won't have too many conflicts, but if you do then PR into master and I will take care of that myself

**Comment by Equbuxu** [comment]
> I finally did it :)

Actually, I didn't realize you've used the same branch as in your previous PR (that's kinda messy). Disregard what I said about rebasing

**Comment by tomaszkot** [comment]
> #130 needs more work. Document -> Resize Document dialog has "1" as the default percentage. Typing in a large value like 99999 and resizing causes a crash. The UI looks awkward, the textbox isn't centered relative to the "percentage" label and the label itself is offset from the radio button. The radio buttons need to be styled to fit the rest of the program.

I think I did them all.
