### ISSUE TITLE
Fix max main window height

### ISSUE THREAD

**Issue by CPKreuz** [PixiEditor/PixiEditor#178]
Currently the max window height is set to `SystemParameters.MaximizedPrimaryScreenHeight` [(see here)](https://github.com/PixiEditor/PixiEditor/blob/master/PixiEditor/Views/MainWindow.xaml.cs#L34)

This works fine as long as the user doesn't put PixiEditor on a monitor with a different resolution or changes the screen resolution while PixiEditor is running

Now, why is the property set in the first place. That's because we're using our own top bar (where the close button and file, select, ... buttons are located), to hide the default windows one we're setting `WindowStyle="None"` this has the side effect that PixiEditor goes over the task bar wich is fixed by setting `MaxHeight`

**Comment by flabbet** [comment]
@CPKreuz Did you fix it in #173?

**Comment by Equbuxu** [comment]
https://stackoverflow.com/questions/20941443/properly-maximizing-wpf-window-with-windowstyle-none
this should help
