### ISSUE TITLE
Extensions (Old 2021)

### ISSUE THREAD

**Issue by CPKreu** [PixiEditor/PixiEditor#205]
# General

Extensions are code libraries which can add small features to PixiEditor without those features being included when downloading PixiEditor.

This not only allows users to add features that they really need but also enables them to quickly develop features for themselves without knowing how the internals of PixiEditor work. 

Extensions should be easy too download and install.

# Planned Features:
(* indicates the priority, max is ****)
(? indicates that will likely not be done)
(+ indicates that this has already been implemented in the extension prototype)
(V.x indicates the version this is planned for)

- [ ] Loading extensions V.4 **** (+)
- [ ] Dependencies
- [ ] Enabling/Disabling extensions V.4 ****
- [ ] Creating custom file parsers V.4 *** (+)
- [ ] Extension Preferences V.? ** (+)
- [ ] Publishing extensions and downloading from within PixiEditor V.? (Probably V.4 too)
- [ ] Cross Application
- [ ] Creating custom windows/filters V.? ***
- [ ] General interaction with PixiEditor V.? (Should come with custom windows) ***
- [ ] Pallets **
- [ ] Custom Tools *
- [ ] Cloud Services * (?)

## Loading Extensions

Loading extensions has already been implemented in #189 but I think it should work a bit differently.

Previously, all .dll files in a certain directory were loaded, and then a certain method was called in which the extension could tell PixiEditor how the extension is called and which file parsers it adds

This conflicts with enabling and disabling

When disabled, extensions should not be loaded, but loading is required to know the name of the extension

I think this can be easily fixed by creating a json file which contains the name, description and other information about the extension. To make sure the end user (who downloads and uses the extension) does not edit/delete this file, extensions should be stored in a ZIP file that is "camouflaged" with a different file extension. Something like `.pixiext` would work

## Dependencies

Extensions should be able to tell that they depend on another extension so that PixiEditor automatically installs it.

It would also be possible to add support for NuGet package

## Enabling and Disabling

Enabling and disabling should be pretty straight forward.

Just save if the extension has been enabled in the local app data

## Creating file parsers

Extensions should be able to add file parsers, but the way people open files within PixiEditor should not change.

Currently file parsers are added on extension load.

If a file extension is already implemented by an other extension, the file parser will just be ignored. **This should be changed**

Opening files from explorer should also work with extensions

## Extension preferences

Extensions should be able to save information that they might need later.

Allowing extensions to add settings to the settings window might also be added.

## Publishing extensions

There should be a service for publishing extension so that a user can easily download extension within PixiEditor and/or from a website.

Using GitHub to store all extensions could work but this still has to be discussed

## Cross Application

There are plans for other projects like PixiViewer, PixiBot and PixiCLI

It would be great if extensions would work with these applications too

## Creating custom windows and filters

Extensions should be able to add custom windows which can be opened from the main menu bar (at the top of PixiEditor where you can save files, etc) or when a user tries saving a file

There should be two types of windows

### Dialogs

Dialogs are simple windows, they can't be docked to PixiEditor (for example the new file dialog which appears when creating a new file)

### Dockable Windows

Dockable Windows are windows that can be docked inside of PixiEditor (for example the color picker and navigation window).

## General interaction with PixiEditor

This should allow the extension to interact with the objects inside of PixiEditor like Documents, Layers and Swatches

## Pallets

Pallets might also be added with extensions

What they do and how they work has to be discussed

## Custom Tools

These are still being designed inside my head.

## Cloud Services

_I'm pretty sure that this is not very useful as cloud service providers probably have their own software for it to automatically sync it from the explorer (e.g. OneDrive)_

Extensions would be able to add a cloud service saving service

PixiEditor would then add a new menu item, called something like this
File > Save to cloud > _Service Name_
or add an autosave option

**Comment by CPKreuz** [comment]
## Custom Windows

I think we can use the XamlReader class for it

## General Interaction

I wanted to put the API in a simple NuGet package which would mean you would have to put PixiEditor.dll also in a NuGet package, I'm not sure if we want this

## Cloud Services

Is that a yes or no?

**Comment by CPKreu** [comment]
Closing this cause this isn't up to data at all

Proper extensions will be released with v2.0
