### ISSUE TITLE
Preview Window doesn't display anything

### ISSUE THREAD

**Issue by CPKreuz** [PixiEditor/PixiEditor#218]
![bird](https://user-images.githubusercontent.com/45312141/127776766-232455b8-1d12-4549-97ac-c95ddf1b5693.PNG)

**Comment by flabbet** [comment]
Did you check the binding errors?

**Comment by CPKreuz** [comment]
No, but the person who fixes this should

**Comment by flabbet** [comment]
Good news, you've won the lottery of grabbing this issue

**Comment by CPKreuz** [comment]
It appears to be fixed in #211
