### ISSUE TITLE
Zoom tool

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#22]
**Is your feature request related to a problem? Please describe.**
There is no way to zoom when using a graphic tablet.

**Describe the solution you'd like**
A zoom tool that would work similar to the one in photoshop or clip studio paint:
Left-click - zoom in
Alt + Left-click - zoom out
Drag right with left mouse button pressed - zoom in 
Drag left with left mouse button pressed - zoom out 

**Describe alternatives you've considered**
Keyboard shortcuts to zoom in/out would be good too

**Comment by flabbet** [comment]
#36
