### ISSUE TITLE
Don't load big files in startup window

### ISSUE THREAD

**Issue by CPKreuz** [PixiEditor/PixiEditor#220]
Currently all files are loaded when the startup window is opened, which might crash PixiEditor because of too much memory consumption.

Checking the file size is probably not enough so checking the width and height of the document/image headers should work

**Comment by flabbet** [comment]
Wouldn't it be better to actually resize the image to preview size?

**Comment by CPKreuz** [comment]
Yes! Specifically the loading of the `PreviewBitmap`
