### ISSUE TITLE
Add the rest of the view models to the service provider

### ISSUE THREAD

**Issue by CPKreuz** [PixiEditor/PixiEditor#222]
There are currently only 3 view models that can be injected into tools.

We should add the rest in the `ViewModelMain.ConfigureServices` method and use them in the `ViewModelMain.Setup` method

**Comment by Xiphereal** [comment]
Hi! Hope I can help with this. I have a couple of questions:

Which are those 3 ViewModels? I see `StylusViewModel`, `WindowViewModel` & `ToolsViewModel` being registered [here](https://github.com/PixiEditor/PixiEditor/blob/fafb0f43d62c219402742e3a16851f3d6906bf0e/PixiEditor/Views/MainWindow.xaml.cs#L81)?

I also think I don't quite understand why are the rest of those "non-injectable" ViewModels the ones that must be added to `ViewModelMain.ConfigureServices()`; from my understanding, the injectable ViewModels should be the ones being added to the `IServiceCollection`.

Thanks :)

**Comment by CPKreuz** [comment]
Hi!

Initially, Dependency Injection was only used to add `SubViewModels` to `MainViewModel` that relied on running in a WPF application which meant that the Test's in PixiEditorTest needed to provide a mocked version of the SubViewModel

So all of these SubViewModel's were configured in `MainWindow` and the `Test's` that used `ViewModelMain`

Later I added dependency injection to tools but only added the required ones.

Since the rest of the SubViewModels that aren't injected into ViewModelMain, but created by it, don't care if they're used inside a WPF application they should be added in the ViewModelMain.ConfigureServices() to avoid writing the same code in MainWindow and the Tests

The reason why these need to be added (which I forgot to include in the issue description) is because Tools use Dependency Injection to get services like BitmapManager and ToolsViewModel from the constructor instead of having to call ViewModelMain.Current.BitmapManager Everytime it needs the BitmapManager

I hope that was understandable
