### ISSUE TITLE
quickfill: Merge direct-bitmap into quickfill

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#225]
Apart from drawing directly to layers, the tools' Use function should return a dirty rectangle (the modified area)
Convert tools to draw on layers directly and invoke changes with a correct dirty rectangle on them. This dirty rectangle should then be passed into Layer.InvokeLayerBitmapChange. (this will trigger redraw of the view).

We don't actually have to do this now (finishing quickfill, merging it into master, and then merging master into direct-bitmap is an option), however, I feel like it will be better to do it sooner to avoid large merge conflicts.

**Comment by flabbet** [comment]
Finished merge. Unfortunately most of the tools needs to be rewritten. Also undo for them is not implemented.
