### ISSUE TITLE
quickfill: Fix tests

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#227]

**Comment by Equbuxu** [comment]
Only clipboardcontroller is left

**Comment by Xiphereal** [comment]
Hi, may i help with this issue? I'll need a bit of context for what does "Fix tests" really mean.

**Comment by Equbuxu** [comment]
> Hi, may i help with this issue? I'll need a bit of context for what does "Fix tests" really mean.

Pretty much all of the tests are fixed already, apart from the few ones related to ClipboardController. ClipboardController itself needs to be fully converted to use SkiaSharpB before fixing those, @CPKreuz is working on that.

**Comment by CPKreuz** [comment]
Hi!

I actually don't have much time for working on PixiEditor so if you want you can improve clipboard
