### ISSUE TITLE
Hold down tool key to use the tool temporarily

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#24]
Tool keys should work similarly to other drawing software:
- When a key is pressed shortly the corresponding tool should be selected (this is the current behavior)
- When a key is held down the corresponding tool should be selected only while it is held. Upon releasing the key the tool should automatically be switched to a previously used one. (to be implemented)

**Comment by flabbet** [comment]
Feature is now on [dev](https://github.com/PixiEditor/PixiEditor/tree/dev) branch, introduced in [this commit](https://github.com/PixiEditor/PixiEditor/commit/cb4c900639b17950db55248a5830fe439b8aa6e9)
