### ISSUE TITLE
quickfill: can't pick colors from reference layer

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#243]
The color picker tool only looks at the final rendered image now (the result of combined layer stack) and that doesn't include the reference layer

**Comment by Equbuxu** [comment]
This can be fixed by picking a color from the reference layer and overlying it with the color from the final rendered image. Please do not use screenshots to pick the color though as we want to avoid picking up the transparent background.

**Comment by flabbet** [comment]
@CPKreuz Please investigate if it works, especially with this image (check the silver pixels on lightsaber handle)
![Lightsaber,_silver_hilt,_blue_blade](https://user-images.githubusercontent.com/25402427/144644441-938735f0-c1e9-404d-a2f0-cd20f1c97a29.png)
.

**Comment by CPKreuz** [comment]
> @CPKreuz Please investigate if it works, especially with this image (check the silver pixels on lightsaber handle)
> ![Lightsaber,_silver_hilt,_blue_blade](https://user-images.githubusercontent.com/25402427/144644441-938735f0-c1e9-404d-a2f0-cd20f1c97a29.png)
> . 

I guess I forgot we're not living in a perfect world and not all images are a perfect square
