### ISSUE TITLE
Reference Layer Improvements

### ISSUE THREAD

**Issue by CPKreuz** [PixiEditor/PixiEditor#246]
* Saving reference layers (PixiEditor/PixiParser#9)

* Moving and Resizing, preferably with tools

* Reloading reference layers either manually or when the file system notices a change

**Comment by CPKreuz** [comment]
PixiEditor would store the GUID and file path in the local app data preferences

**Comment by flabbet** [comment]
Moving and scaling is a must, although idk how it could be done using tools. I would place a move and scale button in reference layer panel.
