### ISSUE TITLE
"incognito" in discord rich presense is wrong

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#251]
Settings -> Discord -> Uncheck "Show document name"
Incognito means to hide your identity, not the document you are editing. I would just remove that word from there and maybe say "editing an image" instead of "editing something"

**Comment by CPKreuz** [comment]
Fixed in #211 https://github.com/PixiEditor/PixiEditor/pull/211/commits/136a7edc4203412e5700148cd61442eb08161a9f
