### ISSUE TITLE
Don't show document details in rich presense by default

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#252]
Document details (name especially) can contain sensitive information and it might not be obvious to everyone that this info is publically displayed by default

**Comment by flabbet** [comment]
I agree, this should be disabled by default

**Comment by CPKreuz** [comment]
Fixed in #211 https://github.com/PixiEditor/PixiEditor/pull/211/commits/136a7edc4203412e5700148cd61442eb08161a9f
