### ISSUE TITLE
Mouse events are handled poorly

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#259]
PixiEditor uses two sources for mouse events which are wpf and global mouse hook. The events that come from wpf don't always make sense, e.g. mousedown is not followed by mouseup. There is also a third mouse data source (which shouldn't be used): Mouse.LeftButton and Mouse.RightButton. Those are convenient as they let you easily check the mouse state, but they aren't synchronized with the events.

A single robust system for mouse input handling needs to be designed. It should:
- Combine many event sources into one
- Provide consistent data: MouseDown should always be followed by MouseUp, every way to check current or previous mouse state should be synchronized with the MouseDown and MouseUp events
- Provide two sources of events, one for precise mouse movement, and one that ignores sub-pixel movements and reports integer positions on the canvas
- Be fast, it should be able to handle at least 1000 mousemove events per second

**Comment by flabbet** [comment]
Is it solved?

**Comment by Equbuxu** [comment]
> Is it solved?

I still need to test performance so I'll keep this issue for now
