### ISSUE TITLE
quickfill: Lagspike when starting to use a tool

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#260]
Every time you start drawing with a pen you get a lag spike causing some of the inputs to get dropped. This results in a jump that looks like a straight line. The lag spike is probably caused by StorageBasedChange saving the canvas, but the core issue goes much deeper. Mouse input should be recorded in a thread that is separate from drawing to make sure we don't miss inputs. Still, we can at least investigate where the lag is coming from and optimize something to improve the situation

**Comment by flabbet** [comment]
I have some a bit hacky solution, what about creating a StorageBasedUndo when selecting the tool, instead of clicking? If user doesn't draw anything, undo change will be deleted

**Comment by Equbuxu** [comment]
> I have some a bit hacky solution, what about creating a StorageBasedUndo when selecting the tool, instead of clicking? If user doesn't draw anything, undo change will be deleted

It would make more sense to save the current stare of the canvas right after a tool is used because users might change tools without actually drawing or use the same tool  multiple times. I don't see a straightforward way to implement it though as right now tools keep track of their changes themselves, but we would have to store the change elsewhere and then possibly discard it if the user changed layer or chose to use a tool that needs a custom undo process.

Still, we first need to make sure that undo is the cause of the lag

**Comment by flabbet** [comment]
I can confirm that it is caused by default undo method.

**Comment by flabbet** [comment]
Fixed
