### ISSUE TITLE
quickfill: Base layer disappears from the file causing a crash

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#266]
Load  [this](https://github.com/PixiEditor/PixiEditor/files/7676941/save.zip) file. Draw a line (it will disappear because the layer is hidden). Press Ctrl+Z to crash PixiEditor. The crash is caused by the base layer disappearing from the layers list. It is definitely there right after the document is loaded, but by the time you press undo something happens to it. LayerStructure.GetGroupByLayer then tries to find that layer and fails.

**Comment by flabbet** [comment]
Can't reproduce no more
