### ISSUE TITLE
NullReferenceException when starting Pixieditor.

### ISSUE THREAD

**Issue by StarlkYT** [PixiEditor/PixiEditor#269]
Opening Pixieditor with missing photo files raises an `System.NullReferenceException` in:
1. ImageFileMaxSizeChecker.IsFileUnderMaxSize()
2. RecentlyOpenedDocument.LoadPreviewBitmap();

**Describe what you tried to do in order to fix it**
Add a null check. For `LoadPreviewBitmap` I had to check if `bitmap` was null.

**Comment by flabbet** [comment]
Could you please provide:
- A version of PixiEditor you were using 
- crash file, which can be found in `AppData\Local\PixiEditor\crash_logs`.

I understand that it crashes when photo you used to open with PixiEditor is no longer present at given path, right?

**Comment by StarlkYT** [comment]
> Could you please provide:
> 
> * A version of PixiEditor you were using
> * crash file, which can be found in `AppData\Local\PixiEditor\crash_logs`.
> 
> I understand that it crashes when photo you used to open with PixiEditor is no longer present at given path, right?
Yep.

I used the latest version from the official website.

Crash log: <https://pastebin.com/FJVxQaNR>

**Comment by flabbet** [comment]
Closing, since issue is probably already fixed
