### ISSUE TITLE
Support more export formats

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#278]
Currently, PixiEditor only supports .png and .pixi file formats. It would be nice to add more ones, like .jpg, .bmp, .tiff and .webp

**Comment by tomaszkot** [comment]
I can do is as a common code along with #277

**Comment by tomaszkot** [comment]
I did a first attempt to it, but when pressing 'Creating Pull Request' in VS it still appends to existing PR instead of creating a new one :/.

**Comment by Equbuxu** [comment]
> I did a first attempt to it, but when pressing 'Creating Pull Request' in VS it still appends to existing PR instead of creating a new one :/.

A pull request is just a request to merge a branch. Github just shows all of the commits you wanna merge. So if you commit to the same branch those commits will show up in the same PR.

Now, I see that you've managed to make a separate PR which is #319, but there is a problem with it because it contain all commits from #312. At the momen

**Comment by Equbuxu** [comment]
All of this makes me think we should improve our contribution manual because there is a simple rule that can help avoid all of your issues: before working on a feature make a new branch for it based on master. Never commit directly to master. You've already commited to master in #312 and because of that you can't really make branches based on your master anymore as they will contain those commits

**Comment by Equbuxu** [comment]
By the way, github isn't a very convenient place to discuss this, if you use discord you should join our chat https://discord.gg/qSRMYmq, that's where most of the development discussions happen

**Comment by flabbet** [comment]
Yup, we will merge #319 when #312 will be ready to merge
