### ISSUE TITLE
Disable maintain aspect ratio by default

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#286]
Back when I first started using PixiEditor I found it quite annoying for "maintain aspect ratio" to be selected by default. It always caught me off guard as I expected to fill both fields myself. I've just decided to look through a bunch of software and found that "maintain aspect ratio" is actually a rare feature on the new file dialog, only 1 out of 5 apps I tested had it. And that one app (paint.net) has it disabled by default. I think it would make more sense to have it disabled too, at least in the "new file" menu, as it can be more useful when resizing the image.

Another thing to say is that by having it enabled by default we assume that everyone wants a square image, and most of the time I actually don't want a square image for my drawings

**Comment by flabbet** [comment]
Agree

**Comment by CPKreuz** [comment]
Fixed in https://github.com/PixiEditor/PixiEditor/pull/211/commits/25f7a16064c4776c96acf2694f2e0c21e046c3b2
