### ISSUE TITLE
Change default file size to something more reasonable than 16x16

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#287]
I get the pixieditor is a pixel art software, but like, how often would one really want to draw tiny sprites? I'd make it 96x96 or even 128x128

**Comment by CPKreuz** [comment]
Changed it to 64x64 in
https://github.com/PixiEditor/PixiEditor/pull/211/commits/25f7a16064c4776c96acf2694f2e0c21e046c3b2
