### ISSUE TITLE
[Feature Request] Make Button text smaller

### ISSUE THREAD

**Issue by therealbluepandabear** [PixiEditor/PixiEditor#307]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Currently most button's text is too large in comparison to the button itself:

![image](https://user-images.githubusercontent.com/50536495/148714202-da054aff-63af-4a5a-b0c4-fadd1b127e31.png)

Making the text size smaller will improve the UI by a lot, here is an example of a better designed button:

![image](https://user-images.githubusercontent.com/50536495/148714307-40b424ac-3efe-48af-982b-b2e057ff9f02.png)

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by flabbet** [comment]
Yeah, this is a nice suggestion. We want to redesign buttons and some UI elements as well
