### ISSUE TITLE
[Feature Request] Animation support

### ISSUE THREAD

**Issue by tom-o-the-developer** [PixiEditor/PixiEditor#308]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

I'm personally a massive fan of your app right now, and I definitely think you have a chance to compete with Aseprite, although in order to do this you might want to think of adding animation support using onion skinning (using frames) in the future. Many pixel artists love to create animations.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by flabbet** [comment]
Yup, this is planned for v0.4 or v0.5

**Comment by elv1s42** [comment]
+1 for animation support!
