### ISSUE TITLE
Undo/Redo break when resizing the canvas

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#309]
https://user-images.githubusercontent.com/29402050/149121440-f50d2cd1-6fe7-4432-9f74-74db06d85290.mp4

**Comment by flabbet** [comment]
This has to do something with offset, drawing second line from (0,0) makes bug not happen

**Comment by flabbet** [comment]
Ok, I am no longer sure about that

**Comment by flabbet** [comment]
Fixed #328
