### ISSUE TITLE
Recently used files - can I remove items from it?

### ISSUE THREAD

**Issue by tomaszkot** [PixiEditor/PixiEditor#316]
I deleted files I recently used but the keep popping up on HelloTherePopup dialog and are available in File->Recent menu. When clicking one in the menu it disappears from the menu but after restarting app it's again there.

**Comment by Equbuxu** [comment]
It's strange that they come back after disappearing. I think right now there is no way to clear the list or to remove individual items, it would be nice to add these features at some point.

**Comment by CPKreu** [comment]
This was done with 6d1bbc7ec73f6506c8adf024f45a16d57129489b
