### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by flabbet** [PixiEditor/PixiEditor#321]
A crash I found on this branch:

Draw something
Select it
Ctrl+C
Remove selection
Delete base layer
Draw something
Paste
Undo x3
Redo
Draw something
Not sure if you want to fix it here, you can move this into an issue

**Comment by Equbuxu** [comment]
Better repro:
1. Delete Base Layer
1. Undo
1. Redo
1. Draw something

**Comment by flabbet** [comment]
When I was debugging it, I noticed that redoing delete base layer doesn't restore layer GUID value
