### ISSUE TITLE
Shared tool settings are broken

### ISSUE THREAD

**Issue by flabbet** [PixiEditor/PixiEditor#329]
Reproduce: 
- Change pen tool size to 5
- Switch to line tool

Expected: Line size = 5
Actual: Line size = 1

**Comment by Equbuxu** [comment]
this is a nice bug please no fixing

**Comment by flabbet** [comment]
Let's make it a option in settings

**Comment by flabbet** [comment]
I fixed it as it was before, option in settings will be added later
