### ISSUE TITLE
PixiEditor fails to load recovered files even though they were successfully saved

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#357]
1. Open this file [before_clip.zip](https://github.com/PixiEditor/PixiEditor/files/8098952/before_clip.zip)
2. Draw something
3. Crash
4. Press recover files
5. PixiEditor opens with no files, even though the file was saved successfully and loads fine if you extract and open it manually

**Comment by flabbet** [comment]
@CPKreuz fix this
