### ISSUE TITLE
MAJOR lag at higher zoom levels while using the brush

### ISSUE THREAD

**Issue by AlmosYT** [PixiEditor/PixiEditor#370]
**Describe as detailed as possible when it happens**

The pencil tool starts lagging behind if you increase the zoom level. Could also have something to do with poll rate however it seems to be unrelated.

**Reproduction steps**

If you are able to, include steps to reproduce bug

1. Create a new file with a size like 300x300
2. Zoom out
3. Draw anywhere using the pencil tool
4. Observe that the drawing is smooth
5. Zoom in
6. Draw anywhere using the pencil tool
7. The tool lags behind to user input

**Expected behavior**

The tool should be smooth as it isn't very resource-intensive.

**Include related files,**

Demonstration:
![gp353epW2w](https://user-images.githubusercontent.com/62188528/155200451-4b1b8fe8-98af-42c5-ad96-29fc150dd752.gif)

**System information**

Windows version: 11 (latest)
High-end specs

**Additional context**

The mouse being used is the Steelseries Rival 700

**Comment by flabbet** [comment]
This issue is most likely already resolved
