### ISSUE TITLE
Logo is not aligned

### ISSUE THREAD

**Issue by flabbet** [PixiEditor/PixiEditor#388]
![image](https://user-images.githubusercontent.com/25402427/156745688-2030addd-efac-4761-908d-8069fc431e0d.png)

**Comment by Equbuxu** [comment]
What if I told you that the square on top is in fact a rectangle

**Comment by flabbet** [comment]
even worse

**Comment by flabbet** [comment]
![PixiEditorLogo](https://user-images.githubusercontent.com/25402427/157181103-3448ab7f-a0c8-4aca-9769-3f528362f78b.png)

Improved

**Comment by flabbet** [comment]
It's uneven in sticking point. sigh...

**Comment by flabbet** [comment]
![PixiEditorLogo](https://user-images.githubusercontent.com/25402427/157181584-e47e4fd5-3973-43c2-9645-10aa11cbe7b4.png)

Now

**Comment by CPKreuz** [comment]
This just looks... wrong in my opinion
Maybe it's better unaligned and as a rectangle?

**Comment by flabbet** [comment]
No, if you'd make square smaller, bottom rectangle would not be aligned anymore. I also think this looks weird

**Comment by Equbuxu** [comment]
are you guys sure the logo actually needs to be fixed? like it's out of proportions and things aren't aligned but it never bothered me

the new one looks a bit weird probably just because it's different

**Comment by flabbet** [comment]
To be honest, no
