### ISSUE TITLE
Mouse input desync because of multiple input sources

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#39]
**The issue**
When moving and clicking at the same time mouseDown event sometimes doesn't fire fast enough, meaning mouseMove event might fire before it. Since the mouse is already pressed down when mouseMove fires [this](https://github.com/PixiEditor/PixiEditor/blob/04f032bf084f1c1aab69b07ec4256bf4afd2e3c4/PixiEditor/Models/Controllers/BitmapManager.cs#L138) check passes and zoom tool gets executed updating viewport zoom ([ZoomPercentageChanged](https://github.com/PixiEditor/PixiEditor/blob/04f032bf084f1c1aab69b07ec4256bf4afd2e3c4/PixiEditor/Views/MainDrawingPanel.xaml.cs#L106)). Since mouseDown event has yet to fire at this point [SetClickValues ](https://github.com/PixiEditor/PixiEditor/blob/04f032bf084f1c1aab69b07ec4256bf4afd2e3c4/PixiEditor/Views/MainDrawingPanel.xaml.cs#L139) function has yet to be called as well, meaning that ([ZoomPercentageChanged](https://github.com/PixiEditor/PixiEditor/blob/04f032bf084f1c1aab69b07ec4256bf4afd2e3c4/PixiEditor/Views/MainDrawingPanel.xaml.cs#L106)) function used the old value of [ClickScale](https://github.com/PixiEditor/PixiEditor/blob/04f032bf084f1c1aab69b07ec4256bf4afd2e3c4/PixiEditor/Views/MainDrawingPanel.xaml.cs#L117). This causes a jump, similar to one cause by releasing mouse button outside viewport.

**A hacky fix**
ZoomPercentageChanged function already executes SetClickValues function when percentage == 100. We could add a flag, something like "mouseWasUp", and add another check to execute SetClickValues if mouseWasUp is true.

**A more proper fix**
I feel like it would make more sense to track mouse state manually based on the events instead of relying on System.Windows.Input.Mouse.LeftButton. This will ensure mouse state is always in sync with events

**Comment by flabbet** [comment]
I probably fixed this issue, due to events desync, there was a bug, where the drawing was moved along with mouse. I added `LeftMouseState` to `MouseMovementController` and now it should be used instead of `Mouse.LeftButton`, it is synced with `MouseUp` and `MouseDown` events. Still, more investigation required to confirm this issue is actually resolved.

**Comment by flabbet** [comment]
@Equbuxu fixed right?

**Comment by Equbuxu** [comment]
yes
