### ISSUE TITLE
Pen keeps eraser size

### ISSUE THREAD

**Issue by Rindecision** [PixiEditor/PixiEditor#391]
V 0.1.7.4
Win 11
Asus ROG Flow 13.4
Raphael 520(Pen)

I discovered it while using my stylus but it also happens when I use use my trackpad to click between pen>eraser>pen.

I had my pen size at 1 and my eraser at 3. I was using the pen, when I swapped to eraser the size went to 3 as I had set it, but on returning to pen it had maintained the size of 3. When I change the pen size back to 1 and try again the bug persists. I tried altering the pen size to larger and it still reverted it to whatever the eraser size is regardless.

**Comment by flabbet** [comment]
It is fixed in #379. I'm gonna publish new development release soon
