### ISSUE TITLE
Design a new logo

### ISSUE THREAD

**Issue by flabbet** [PixiEditor/PixiEditor#40]
The current logo is nice, however, we would gladly use something fresh. 

- Dimensions should be at least 512x512 pixels.
- If we choose your logo, you should send us a PNG and a work file (.PSD, .AI, etc.)

_By submitting you agree to give us a full right to all files you send._

**Comment by chamindujs** [comment]
I would like to work on this issue. Can you assign me to design a logo?

**Comment by flabbet** [comment]
Done, go for it

**Comment by chamindujs** [comment]
**Quick question:** Can I also change the logo in the app and open a PR, after uploading it here?

**Comment by flabbet** [comment]
Sure

**Comment by chamindujs** [comment]
![logo](https://user-images.githubusercontent.com/41909955/94757145-11f37b00-03b7-11eb-9a9a-6252fa896a18.png)
 Here is a fully redesigned futuristic, yet simple logo.

**Comment by flabbet** [comment]
Hey, nice design, we discussed on discord and decided to keep the current one, this one a little deviates from the overall theme of the application, the program is indeed for pixel-arts, but as you might notice, the UI is clean and not in a pixelated style. We would love to see more work from you, and thanks for submitting it!

**Comment by royquilor** [comment]
Hi, are you accepting ideas? Would love to share a concept

**Comment by chamindujs** [comment]
@flabbet Hey, can you accept my PR and add **hacktoberfest-accepted** label to my PR? So my contribution would count towards 
[Hacktoberfest](https://hacktoberfest.digitalocean.com/).

Please be kind enough to consider my message.

**Comment by flabbet** [comment]
It's a lot of time for Hacktoberfest to finish, your logo seems like no more than 30 minutes of work (sorry if I am wrong), I appreciate the effort, however, It's too little, If you apply the changes I suggested in my comment from 8 days ago, I'll add hacktoberfest accepted label.
Thanks

**Comment by cnikhil04** [comment]
I have made one design, with the considerations mentioned above.
Kindly assign to have a look at it

**Comment by cnikhil04** [comment]
Pull request reference: #72 
![PixiEditor](https://user-images.githubusercontent.com/63284684/95629408-7ee4d000-0a9d-11eb-8ea9-fe829b0deee6.png)

**Comment by chamindujs** [comment]
![logo](https://user-images.githubusercontent.com/41909955/95657321-9c637980-0b31-11eb-9599-6bf9e23b5eb3.png)
![logo1](https://user-images.githubusercontent.com/41909955/95657525-8f935580-0b32-11eb-8b45-5bdff2daa42e.png)


Tried 2 new logo designs with a sophisticated look. What do you think?

**Comment by flabbet** [comment]
@cnikhil04 Awesome work, I like it, but I like the current P shape, could you:
-  make the P head so it's square, and arrange the bottom line so it looks similar to the current one
- change the color from black to more grayish
- Instead of a pen symbol, insert a brush 
- Something isn't right with the "E", I think it makes the logo too complicated, we should keep it simple. I guess it should be focused on the "P", maybe remove "E" or arrange it so it is an addon, not part of the main design.

**Comment by cnikhil04** [comment]
![SAMPLE pe](https://user-images.githubusercontent.com/63284684/95889652-4b0cf180-0da0-11eb-8ff5-f5e4901850b4.JPG)

**Comment by flabbet** [comment]
Hey! Thanks for your contributions, you made awesome work. We've discussed on discord and concluded that 'e' is not visible in logo size, so it's redundant. And the pen is making the logo, too complicated. So the thing we are left with is almost the same as the original logo, except a hole in 'P'. I like your work and if you still would like to make changes or design something new, I recommend you join our [Discord](https://discord.com/invite/qSRMYmq) for faster feedback. Keep the great work!

**Comment by cnikhil04** [comment]
Thanks for the feedback, I believe these logos have been designed by all your above-mentioned constraints and feedbacks. 
Personally feel representative logo suits best for any company rather than just any symbol.
It would be great if you appreciate my invested time, efforts, and designs by labeling it as hacktoberfest-accepted 
PR reference: #72

**Comment by flabbet** [comment]
I already accepted your PR, so it counts towards hacktoberfest :)

**Comment by cnikhil04** [comment]
Thanks

**Comment by flabbet** [comment]
Closing the issue, because we are satisfied with the current logo.
