### ISSUE TITLE
Windows 98 window headers

### ISSUE THREAD

**Issue by aventurain** [PixiEditor/PixiEditor#410]
**Reproduction steps**

1. Move dockable window out from screen.
2. Return it.

![image](https://user-images.githubusercontent.com/64274465/177210066-f2d8e4f8-2b98-433c-9e7f-27a22b5de69c.png)

**Comment by flabbet** [comment]
@Equbuxu did you by any chance fixed it?

**Comment by CPKreu** [comment]
Not sure if this is still on WPF but definitely no longer on master as that uses Avalonia
