### ISSUE TITLE
Moving window crash

### ISSUE THREAD

**Issue by aventurain** [PixiEditor/PixiEditor#411]
**When it happens**

Moving Pixel Editor windows around will stops the program. And you won't be able to move the cursor out of the program window.

**Reproduction steps**

Unknown

**Related files,**

![image](https://user-images.githubusercontent.com/64274465/177210743-0f0f143c-68f3-4cb3-ad33-1a8f4c905983.png)

**Additional context**

Shut down Pixi Editor with task manager helps, but does not create a crash log

**Comment by Equbuxu** [comment]
An issue that mostly fits this description was fixed in #414, so chances are pixieditor won't hang anymore. Needs testing thought

**Comment by Equbuxu** [comment]
fixed for good in #583 and #600
