### ISSUE TITLE
Text box select bug

### ISSUE THREAD

**Issue by aventurain** [PixiEditor/PixiEditor#412]
**When it happens**

It happens in Pallet color selection window
![image](https://user-images.githubusercontent.com/64274465/177212001-f5f69861-3cab-4eef-9ff8-28ba640e96dc.png)
and Settings window
![image](https://user-images.githubusercontent.com/64274465/177212058-2df816bd-7525-456c-a792-2fedeb144014.png)

window will minimize when you follow next steps: 

**Reproduction steps**

In Pallet color selection window:
If you release the mouse button outside the window during the text selection

In Settings window:
Bug happening when you select text and click in window, but outside text box.

**Expected**
The window should not minimize

**Comment by Bayrem00** [comment]
The color map loss of focus bug is part of the ColorPicker code and can not be fixed on this repo.

**Comment by Equbuxu** [comment]
related #418
