### ISSUE TITLE
Space transient key stops functioning correctly after you choose a tool with a shortcut

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#419]
1. Start the app, make a new canvas
2. Select Circle Tool
3. Press B to select Pen Tool
4. Hold down space for a few seconds to temporarily switch to Move Viewport Tool
5. Release space
6. The tool isn't switched back to pen

**Comment by flabbet** [comment]
Fixed in #414 @Equbuxu please test

**Comment by Equbuxu** [comment]
seems to work
