### ISSUE TITLE
Huge Lagspike when selecting large areas.

### ISSUE THREAD

**Issue by PixlaStudios** [PixiEditor/PixiEditor#422]
When I select a large area in a picture the program freezes up.

Example:
1. Create new file with size 1028x1028 (Or Bigger)
2. Select The Entire area.
3. Fps drops to 1 - 2.

What should happen:
It should still run fine, And not drop to 1fps.

Files:
![issue](https://user-images.githubusercontent.com/108760829/184405143-db6a3d40-c2ff-4876-bf22-b336bd253870.png)

System Infomation

Windows version: 11/10/8/7
PixiEditor version: (for example: 0.1.8.0)

**Comment by flabbet** [comment]
Hello, yeah. We are aware of this issue, and we already fixed it. It will be available in next version :)
