### ISSUE TITLE
GUI adds multi-language support

### ISSUE THREAD

**Issue by wcxu21** [PixiEditor/PixiEditor#423]
Hi, dear developers.
I am from China and work in the design industry.
Can you add multilingual support for this pixel app?
I can assist in translating the Simplified Chinese language.
Thank you for your work!

**Comment by flabbet** [comment]
Hello, you can check out this repo. We are already gathering translations for implementation. There is already Chinese translation but it may lack some texts already https://github.com/PixiEditor/editor-translations

**Comment by wcxu21** [comment]
Thank you for your reply, and I look forward to adding multilingual support soon.
