### ISSUE TITLE
The key for translations is missing

### ISSUE THREAD

**Issue by Loweredgames** [PixiEditor/PixiEditor#426]
a section for translations is missing in the program.

**Additional context**
I saw that in the project https://github.com/PixiEditor/editor-translations the English translation (original) is missing, you should add it and improve the program by including translations.

**Comment by flabbet** [comment]
Hi, yeah, we are planning to add translations, as you noticed. But this is planned after releasing version 1.0

**Comment by Loweredgames** [comment]
> Hi, yeah, we are planning to add translations, as you noticed. But this is planned after releasing version 1.0

ok thanks :)

**Comment by Equbuxu** [comment]
Yeah, that repo exists because some people wanted to contribute translations despite them not being supported yet. We'll eventually collect all the english strings from the source code and make a reference english translation, but for now the actual UI is the only reference

**Comment by Loweredgames** [comment]
ok thanks
