### ISSUE TITLE
Panning after rotating selection yeilds weird results

### ISSUE THREAD

**Issue by flabbet** [PixiEditor/PixiEditor#436]
Video

https://user-images.githubusercontent.com/25402427/205437896-29d15227-d5ac-4b83-988f-bd5272af13ff.mp4

**Comment by flabbet** [comment]
Fixed in #433

**Comment by flabbet** [comment]
Reopening, because now tool change makes transform apply, and for example you cant rotate "back" without loosing pixels

**Comment by Equbuxu** [comment]
idk when but this was fixed
