### ISSUE TITLE
Change object based settings to typed generics

### ISSUE THREAD

**Issue by flabbet** [PixiEditor/PixiEditor#44]
**Is your feature request related to a problem? Please describe.**
Using tool Settings requires to manually cast `object` to the requested type, this is not comfortable to use and might make it more fragile to errors.

**Describe the solution you'd like**
Change `Setting` class to `Setting<T>` where `T` is a value type of setting. Currently to get `ToolSize` setting we need to do `(int) Toolbar.GetSetting("ToolSize").Value` but something like `Toolbar.GetSetting<int>("ToolSize").Value` would be better.

**Comment by anilkhandei** [comment]
@flabbet  I am trying to convert settings class to a generic class. I wonder how to handle the LoadSharedSettings that is defined in the Toolbar class, any tips?

**Comment by flabbet** [comment]
The simplest solution I can think of is that the top parent class would be the current implementation of `Setting`, that operates on objects, and then write a wrapper class that implements generic `T` type, like that
```csharp
class Setting<T> : Setting
```

After you do that, you will still have backward compatibility, so you probably won't need to change anything in the `Toolbar` class.

**Comment by ArtemK123** [comment]
Hi, I would like to try this one. Could you please assign the issue to me?

**Comment by ArtemK123** [comment]
Here is a pull request for the issue
https://github.com/PixiEditor/PixiEditor/pull/66

**Comment by flabbet** [comment]
Closed in #66
