### ISSUE TITLE
Create grid lines for canvas

### ISSUE THREAD

**Issue by flabbet** [PixiEditor/PixiEditor#45]
# Overview
There should be an option to enable grid lines, which will show over the canvas, to improve the visibility of individual pixels.

# Implementation idea

User control, which will sit inside the canvas.

# Additional things

- Menu item to enable/disable grid lines
- Shortcut (Maybe Ctrl + ')

**Comment by yoshivb** [comment]
Hi! So I would like to take a look at this one and had a few questions.

**Where should this menu item reside?**
I am not sure if it being under "Document" would be the best.
Maybe adding a new "View" menu and putting it under there? 
Or did you have something else in mind?

**Would a simple approach where the grid is relative to the scale of each pixel on the screen be acceptable?**
As in when you have a 4x4 document the grid would be rather thick and when you have a 50x50 document it would be considerably thinner unless you zoom in.
Example: 4x4 fully zoomed in
![image](https://user-images.githubusercontent.com/9098909/94992127-1458ff00-0588-11eb-9de5-8ba09fbdb845.png)

Example: 50x50 zoomed to take up roughly the same size on screen
![image](https://user-images.githubusercontent.com/9098909/94992181-7e71a400-0588-11eb-8a04-48edc32c4952.png)

**Comment by flabbet** [comment]
Yes, the `View` menu is a good place to store the setting, What do you mean under Document? My initial idea was something like that
```xaml
<PixelGridLines>
    <Canvas/>
</PixelGridLines>
```

Where `<PixelGirdLines>` is the control that overlays lines on its child. This is just a thought, you can do it another way.

Yes, the thickness of lines should be consistent. For example here is 4x4 zoomed-in other graphics software
![image](https://user-images.githubusercontent.com/25402427/94992420-3bb0cb80-058a-11eb-81b1-5abce5a6cabc.png)

And here is 50x50
![image](https://user-images.githubusercontent.com/25402427/94992430-48352400-058a-11eb-9d35-5a8dee5a29b7.png)

We want to achieve a similar effect. As you can see on 50x50 there are "groups" of lines, 5x5 big squares with 10x10 individual pixels inside. It should be dependent on the zoom percentage. As far as I remember ZoomPercentage in `ViewModelMain`  stores only changes done by `ZoomTool`, so you would need to update it in `<MainDrawingPanel>` control but I might be wrong.

**Comment by yoshivb** [comment]
The first question was regarding the enable/disable menu item.
Whether it should be under "Document" (like shown below) or possibly a new menu?
![image](https://user-images.githubusercontent.com/9098909/94992670-eb3a6d80-058b-11eb-966f-b600553a41f4.png)

**Comment by flabbet** [comment]
I would add it to the new Menu called `View`

**Comment by flabbet** [comment]
Closed in #154
