### ISSUE TITLE
Implement image hashing for image comparison.

### ISSUE THREAD

**Issue by flabbet** [PixiEditor/PixiEditor#50]
**Is your feature request related to a problem? Please describe.**
At the moment implementation of whether image changed, since the last edit is very naive, it works on Bitmap and Layer events, it does not know about the real state of the image. The perfect solution would be a hash comparison, this way we would know if the bitmap really changed.

**Describe the solution you'd like**
A class or extension that would calculate the hash of the final bitmap and use it to check if the program needs to show "Document was modified. Do you want to save changes?" dialog.

Since it will be only calculated on save and application close event, it doesn't need to blazingly fast, but it should be fast enough not to cause a visible delay between clicking the exit button and showing the unsaved changes dialog.

**Comment by uuksu** [comment]
Hello!

I might take a look of this for Hacktoberfest.

I was wondering why do you think that using the events is naive in this case? Could calculating a checksum be a little bit overkill here? Could this be solved simply by implementing Comparer for the Document (compare width and length and pixel by pixel) or using for example Undo stack for determining if there is changes since opening the document?

**Comment by flabbet** [comment]
Yes, I thought about that too. It might be overkill, using events is naive, since any event can fire, and It might show that something changed, where in reality, it didn't. You can do it any way you want, checksum is just the first thing that came into my mind. The comparer for the document sounds nice. The goal here is to improve detecting changes and displaying a warning on exit

**Comment by uuksu** [comment]
I implemented these changed to my fork so you can already review this if you want:
https://github.com/uuksu/PixiEditor/commit/1c514b5665795608cd93d5b4731e6889a4ef9d5c

My changes seem to fix this isse and #49 as well.

I will create a PR when Hacktoberfest begins so this will be counted towards it.
