### ISSUE TITLE
fail to build with vs2017 on windows

### ISSUE THREAD

**Issue by LeiYangGH** [PixiEditor/PixiEditor#503]
clone latest code, checkout 1.0.0.1 tag of release branch(actually also tried lastest master, both not work)
open solution with visual studio, build solution.
or powershell cd to git repo dir, then `dotnet build`, failed.
logs attached.

seems the biggest obstacle is the autogenerated code generated by `PixiEditorGen`. uploaded.
i tried to remove `PixiEditorGen` and build can succeed, but fail to run(of course commands are dependencies).
also investigated some build script such as `azure-pipelines.yml` but had no clue.
could the readme be enhanced on the topic of build project?

Windows version: 11
dotnet version: 7.0.200
vs version: 
Microsoft Visual Studio Community 2022
版本 17.5.3
VisualStudio.17.Release/17.5.3+33516.290

[generated.txt](https://github.com/PixiEditor/PixiEditor/files/11179274/generated.txt)
[dotnet-build.log.txt](https://github.com/PixiEditor/PixiEditor/files/11179275/dotnet-build.log.txt)
[vs-build.log.txt](https://github.com/PixiEditor/PixiEditor/files/11179277/vs-build.log.txt)

**Comment by Equbuxu** [comment]
Hey, yeah, PixiEditor can be a bit finicky to build. You can try (re)installing .NET Standard 2.0 SDK, it can help in some cases (it's needed for the code generators). Removing the project definitely won't work, a significant part of PixiEditor's code is autogenerated. `azure-pipelines.yml` isn't something you need to worry about, it's not used when building locally.

**Comment by LeiYangGH** [comment]
thanks. i'll try it. i never knew .net standard need be installed seperately.

**Comment by flabbet** [comment]
Nah, this is not a solution. I recently had the same problem in clean installation, seems like .NET 7.0.200 is broken for PixiEditor. Please uninstall it and install .NET 7.0.104

**Comment by LeiYangGH** [comment]
unfortuately, installing 7.0.104 remains the same(i've edited global.json with this verison).
and i failed to uninstall 7.0.202 because control panel says it's installed along with vs and in vs installer i cannot find a button to uninstall it.

**Comment by flabbet** [comment]
Open Visual Studio installer app, there you can manage installations. Click modify on VS2022 and remove all .NET components or uninstall VS completely from the installer. Please let me know if it helps

**Comment by LeiYangGH** [comment]
i'm just astonished to know i have to uninstall vs!

PS C:\Users\LeiYang> dotnet --version
7.0.202
PS C:\Users\LeiYang> dotnet --list-sdks
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.201 [C:\Program Files\dotnet\sdk]
6.0.100 [C:\Program Files\dotnet\sdk]
6.0.115 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
7.0.104 [C:\Program Files\dotnet\sdk]
7.0.202 [C:\Program Files\dotnet\sdk]
PS C:\Users\LeiYang>

**Comment by flabbet** [comment]
Well, perhaps you don't need to uninstall it, however if something doesn't work for you, then removing stuff is usually a good step. You must get rid of .NET 7.0.202 completely and PixiEditor compilation should work. So when you type dotnet --version, command prompt should output "7.0.104"

**Comment by flabbet** [comment]
if you just uninstall .NET modules from VS it should work just fine, no need for full uninstallation

**Comment by flabbet** [comment]
Hmm, some update on the topic, the issue might be associated with Visual Studio itself and MSBuild version, not dotnet. I updated Visual Studio 2022 on my pc to 17.5.3 and it broke, can't build PixiEditor anymore. Version 17.4.1 was fine

**Comment by LeiYangGH** [comment]
thanks for the update. maybe i'll wait for next vs update then. is it possible for you to understand what those compile errors mean?

**Comment by flabbet** [comment]
So yeah, we have found the issue in our code, .NET team actually fixed/improved one thing in latest release that our code generators used (and they shouldn't) not the opposite :D, we've already fixed it, try now if it works

**Comment by LeiYangGH** [comment]
works now. i can compile and debug directly using vs. thanks very much!
