### ISSUE TITLE
Direct canvas rendering in AvaloniaUI

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#510]
The approach that we are currently using to render the canvas (a writeable bitmap) has significant performance issues, because it requires transferring updated areas from vram, to ram, back to vram. This should be improved during the avalonia migration. The idea is to have a control with our own vulkan/opengl/metal/whatever texture, which we can draw on directly via the respective graphics api or skia.

Relevant links about how to achieve this in avalonia:

https://github.com/AvaloniaUI/Avalonia/tree/master/samples/GpuInterop
https://github.com/AvaloniaUI/Avalonia/discussions/5432
https://blog.jetbrains.com/dotnet/2021/05/10/case-study-how-gritworld-uses-rider-and-avalonia-to-build-a-powerful-3d-engine/
https://github.com/stride3d/stride/issues/1629

**Comment by CPKreu** [comment]
It's implemented like this on master
