### ISSUE TITLE
Pen up is not detected when pen up occurs outside the application

### ISSUE THREAD

**Issue by hackf5** [PixiEditor/PixiEditor#53]
1. Using the pen tool draw a line and release the mouse button below the bottom of the screen onto the windows task bar.
2. Hold the mouse button down to the right of and off the canvas and drag the mouse onto the canvas.

A diagonal line appears between where you exited the canvas at the bottom and where you entered the canvas on the right. In the image below the green pixel is where I exited the canvas and released the mouse button and the red pixel is where I entered the canvas.

![image](https://user-images.githubusercontent.com/48881437/94579000-40b30980-0270-11eb-8139-4e982ec679fb.png)

**Comment by flabbet** [comment]
Closed in #55
