### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Python-ZZY** [PixiEditor/PixiEditor#575]
** IMPORTANT: Drop the "crash-2023-08-16_17-22-57_338.zip" file in here **
[crash-2023-08-16_17-22-57_338.zip](https://github.com/PixiEditor/PixiEditor/files/12357806/crash-2023-08-16_17-22-57_338.zip)

**Comment by CPKreu** [comment]
Fixed by an lazy @Equbuxu in #583
