### ISSUE TITLE
Art is not visible in the main canvas

### ISSUE THREAD

**Issue by Electr0Gunner** [PixiEditor/PixiEditor#578]
every time i try to draw the canvas stays empty meanwhile layer preview shows the drawing

i just use the normal brush

1. open the software
2. make a new image
3. draw
4. if unlucky no actual canvas drawing

normally in pixieditor it should add to the canvas the drawing

**System information**

Windows 11 latest update
PixiEditor version: latest release x86

Edit:
all versions do the same
64 and 86 and release and developer

EDIT 2!!!!!
IT WORKS IF I  ZOOM OUT

but at 1 spericific zoom it becomes blank again

https://github.com/PixiEditor/PixiEditor/assets/114804446/92742860-c2ef-495f-a422-446bc21f1a04

**Comment by Electr0Gunner** [comment]
also both 64 and 86x versions do the same
dev versions too

**Comment by Equbuxu** [comment]
Hi, this looks exactly like a known issue https://github.com/dotnet/wpf/issues/3817 with intel drivers on some Intel 11 gen CPUs (often found in microsoft surface laptops). If you have an intel 11 gen CPU, the issue can be solved by updating drivers:

https://www.intel.com/content/www/us/en/download/19648/intel-graphics-dch-driver-for-windows-10-windows-11-for-intel-nuc-9-extreme-laptop-kits.html

**Comment by Electr0Gunner** [comment]
Thanks i will try this
