### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by jesus3099** [PixiEditor/PixiEditor#602]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jesus3099** [comment]
Files

**Comment by jesus3099** [comment]
Files

**Comment by jesus3099** [comment]
[xochil2009-main 2.zip](https://github.com/PixiEditor/PixiEditor/files/13763123/xochil2009-main.2.zip)

**Comment by Loweredgames** [comment]
???

**Comment by Equbuxu** [comment]
what are these files?
