### ISSUE TITLE
Moving selected pixels does not maintain the selection format

### ISSUE THREAD

**Issue by SNecronic** [PixiEditor/PixiEditor#604]
### When I select some pixels and after using the tool to move them, it doesn't maintain the shape I requested, staying diagonal instead of rectangular. I've already uninstalled and installed it to see if it was a setting I accidentally activated.

> Image Selected 

![Screenshot_2](https://github.com/PixiEditor/PixiEditor/assets/155754959/9b770a32-fe69-472a-a066-baa1063df90a)

> I just selected the move option, using the shortcut "V"

![Screenshot_3](https://github.com/PixiEditor/PixiEditor/assets/155754959/9ec8c1e4-4a20-46a9-ae1a-663d52d492e7)

> After that, I pressed enter to confirm and the selection changed format

![Screenshot_4](https://github.com/PixiEditor/PixiEditor/assets/155754959/5fd17d88-5c2e-4b23-a0ff-199ed021a357)

**Some considerations:**

- I'm using Windows 11
- I installed the application just a day ago, but yesterday it wasn't like that, I don't know what could have happened.
- If it's not a software problem, could anyone tell me how to solve it?

**Att:** 

- This occurs on large panels, 5000x2500 (quite large for pixel art, but I'm doing several small things)
- Furthermore, it only occurs when I select small areas, when they are large these problems do not occur, but I am making pixel perfect :sob:

**Comment by SNecronic** [comment]
Sorry for English, i'm Brazillian and use Google Translate!

**Comment by Equbuxu** [comment]
Yep, I can replicated this, it must be related to https://github.com/PixiEditor/PixiEditor/issues/534. I'll look into it, but for now I can only suggest using smaller canvases

**Comment by SNecronic** [comment]
I find a way, it's a stupid way, but it works. I have selected larger areas than I want to move. As I made several layers, there are several areas with transparency. So I don't lose the original material!

- Example:

![image](https://github.com/PixiEditor/PixiEditor/assets/155754959/b527977d-9f92-467c-ae7d-d778bf7a5062)

> The blue area is another layer.
