### ISSUE TITLE
Gradient features, better cloning and merging

### ISSUE THREAD

**Issue by quarksaur** [PixiEditor/PixiEditor#620]
It would be nice to introduce some gradient features in this great software. Like linear/radial/conical gradients and quick modification after creating a gradient (just like lines/squares/circles).

I'm currently using Pixilart's editor for this tool and it's a good example. I'd love to see it in PixiEditor too.

Another cool thing would be to merge multiple layers in a new layer and let the original ones stay. It may be practical if you want to change quickly the position of some reference lines like circles and squares in your "blueprint".

Also, please allow the user to copy/paste a selection in the same layer.

Thank you very much.

**Comment by CPKreu** [comment]
Will be implemented, likely in 2.0

In terms of the copy/paste, you can use Ctrl + C to copy the selection and then use Shift + V (not Ctrl) to paste it into your currently selected layer

**Comment by quarksaur** [comment]
Thank you for the tip.
This software has so much potential.
