### ISSUE TITLE
Canvas is not centered correctly when windows UI scaling is not 100%

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditor#683]
![image](https://github.com/user-attachments/assets/72d7752f-f4a4-4133-b941-a7b730cadd3e)
set windows UI scale to anything that's not 100%, press R to center, canvas doesn't end up in the center

**Comment by Equbuxu** [comment]
The pixieditor's "overlay" cursor is also offset from the real cursor with non 100% scaling

**Comment by flabbet** [comment]
Fixed in 2.0.0.29
