### ISSUE TITLE
Add a static code analyzer

### ISSUE THREAD

**Issue by ArtemK123** [PixiEditor/PixiEditor#74]
**Is your feature request related to a problem? Please describe.**
The main problem that the project is open-source, so a lot of people can contribute to the project. Each of them may have a unique style of writing code, so the repository may become the mixin of those styles. I think, it is better to have only one strictly defined style, which is close to the style of repo-owner.

**Describe the solution you'd like**
Add the static code analyzer such as StyleCop.Analyzers for every project in the repo. Add the Custom.ruleset file which defines the style of code in the repo. In all places where the style is not corresponding - the compile-time warning should be added (IDE will highlight it too). Since the reference to the analyzer and ruleset file should be placed in every project - it is better to create Directory.build.props file and move the reference there.

**Describe alternatives you've considered**
The other analyzers may be used. The main idea to have compile-time warnings about the style during the build in order to check them during Github Actions checks and manual code review

**Additional context**
Maybe, the usage of the analyzer is placed somewhere already and I simply haven`t found it. But as far as I found - all checks are done on the IDE-highlighting level only. The problem here is the IDE`s may have different settings for each contributor.

**Comment by flabbet** [comment]
Yes, this is a very good point, the project attracts more and more contributors lately. This is an important todo

**Comment by ArtemK123** [comment]
I can take this. Just add a hacktoberfest label on it, please :)

**Comment by flabbet** [comment]
The whole repo is labeled as Hacktoberfest, you can take any Pull Request, and if I accept it, it will count towards your progress :)

**Comment by ArtemK123** [comment]
Also, I would like to move the .sln file from the PixiEditor project folder to the top of the repo in the scope of this task. Cause it`s quite surprising that the main .sln file is placed in one of the projects.

**Comment by flabbet** [comment]
Yes, this is good idea

**Comment by ArtemK123** [comment]
Ok, so please assign the issue to me.

**Comment by ArtemK123** [comment]
The pull request for the issue:

https://github.com/PixiEditor/PixiEditor/pull/79

**Comment by ArtemK123** [comment]
The pull request was merged, so I will close the issue
